
package pe.gob.sunat.servicio2.registro.consultarucws.service;

import java.util.List;
import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.RequestWrapper;
import jakarta.xml.ws.ResponseWrapper;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.1
 * Generated source version: 3.0
 * 
 */
@WebService(name = "ServicioRucAdmColWebService", targetNamespace = "http://service.consultarucws.registro.servicio2.sunat.gob.pe/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ServicioRucAdmColWebService {


    /**
     * 
     * @param arg0
     * @param arg1
     * @return
     *     returns pe.gob.sunat.servicio2.registro.consultarucws.service.RucByTitularBean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "buscarRucByTitular", targetNamespace = "http://service.consultarucws.registro.servicio2.sunat.gob.pe/", className = "pe.gob.sunat.servicio2.registro.consultarucws.service.BuscarRucByTitular")
    @ResponseWrapper(localName = "buscarRucByTitularResponse", targetNamespace = "http://service.consultarucws.registro.servicio2.sunat.gob.pe/", className = "pe.gob.sunat.servicio2.registro.consultarucws.service.BuscarRucByTitularResponse")
    public RucByTitularBean buscarRucByTitular(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);

    /**
     * 
     * @param arg0
     * @return
     *     returns pe.gob.sunat.servicio2.registro.consultarucws.service.RucByRucBean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "buscarRuc", targetNamespace = "http://service.consultarucws.registro.servicio2.sunat.gob.pe/", className = "pe.gob.sunat.servicio2.registro.consultarucws.service.BuscarRuc")
    @ResponseWrapper(localName = "buscarRucResponse", targetNamespace = "http://service.consultarucws.registro.servicio2.sunat.gob.pe/", className = "pe.gob.sunat.servicio2.registro.consultarucws.service.BuscarRucResponse")
    public RucByRucBean buscarRuc(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg0
     * @param arg1
     * @return
     *     returns java.util.List<pe.gob.sunat.servicio2.registro.consultarucws.service.RucByRucBean>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "buscarRucByRepreLegal", targetNamespace = "http://service.consultarucws.registro.servicio2.sunat.gob.pe/", className = "pe.gob.sunat.servicio2.registro.consultarucws.service.BuscarRucByRepreLegal")
    @ResponseWrapper(localName = "buscarRucByRepreLegalResponse", targetNamespace = "http://service.consultarucws.registro.servicio2.sunat.gob.pe/", className = "pe.gob.sunat.servicio2.registro.consultarucws.service.BuscarRucByRepreLegalResponse")
    public List<RucByRucBean> buscarRucByRepreLegal(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);

}
