
package pe.gob.sunat.servicio2.registro.consultarucws.service;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import jakarta.xml.ws.Service;
import jakarta.xml.ws.WebEndpoint;
import jakarta.xml.ws.WebServiceClient;
import jakarta.xml.ws.WebServiceException;
import jakarta.xml.ws.WebServiceFeature;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.1
 * Generated source version: 3.0
 * 
 */
@WebServiceClient(name = "ServicioRucAdmColWebServiceImplService", targetNamespace = "http://service.consultarucws.registro.servicio2.sunat.gob.pe/")
public class ServicioRucAdmColWebServiceImplService
    extends Service
{

    private static final URL SERVICIORUCADMCOLWEBSERVICEIMPLSERVICE_WSDL_LOCATION;
    private static final WebServiceException SERVICIORUCADMCOLWEBSERVICEIMPLSERVICE_EXCEPTION;
    private static final QName SERVICIORUCADMCOLWEBSERVICEIMPLSERVICE_QNAME = new QName("http://service.consultarucws.registro.servicio2.sunat.gob.pe/", "ServicioRucAdmColWebServiceImplService");

    static {
        // Busca el archivo WSDL dentro del JAR/EXE (carpeta resources/wsdl)
        URL url = ServicioRucAdmColWebServiceImplService.class.getResource("/wsdl/ServicioRucAdmColService.wsdl");
        WebServiceException e = null;
        
        if (url == null) {
            e = new WebServiceException("Error: No se encontró el WSDL en la ruta interna /wsdl/");
        }
        
        SERVICIORUCADMCOLWEBSERVICEIMPLSERVICE_WSDL_LOCATION = url;
        SERVICIORUCADMCOLWEBSERVICEIMPLSERVICE_EXCEPTION = e;
    }
    public ServicioRucAdmColWebServiceImplService() {
        super(__getWsdlLocation(), SERVICIORUCADMCOLWEBSERVICEIMPLSERVICE_QNAME);
    }

    public ServicioRucAdmColWebServiceImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), SERVICIORUCADMCOLWEBSERVICEIMPLSERVICE_QNAME, features);
    }

    public ServicioRucAdmColWebServiceImplService(URL wsdlLocation) {
        super(wsdlLocation, SERVICIORUCADMCOLWEBSERVICEIMPLSERVICE_QNAME);
    }

    public ServicioRucAdmColWebServiceImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SERVICIORUCADMCOLWEBSERVICEIMPLSERVICE_QNAME, features);
    }

    public ServicioRucAdmColWebServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ServicioRucAdmColWebServiceImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ServicioRucAdmColWebService
     */
    @WebEndpoint(name = "ServicioRucAdmColWebServiceImplPort")
    public ServicioRucAdmColWebService getServicioRucAdmColWebServiceImplPort() {
        return super.getPort(new QName("http://service.consultarucws.registro.servicio2.sunat.gob.pe/", "ServicioRucAdmColWebServiceImplPort"), ServicioRucAdmColWebService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link jakarta.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ServicioRucAdmColWebService
     */
    @WebEndpoint(name = "ServicioRucAdmColWebServiceImplPort")
    public ServicioRucAdmColWebService getServicioRucAdmColWebServiceImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://service.consultarucws.registro.servicio2.sunat.gob.pe/", "ServicioRucAdmColWebServiceImplPort"), ServicioRucAdmColWebService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SERVICIORUCADMCOLWEBSERVICEIMPLSERVICE_EXCEPTION!= null) {
            throw SERVICIORUCADMCOLWEBSERVICEIMPLSERVICE_EXCEPTION;
        }
        return SERVICIORUCADMCOLWEBSERVICEIMPLSERVICE_WSDL_LOCATION;
    }

}
