name: Android Build
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del código
        uses: actions/checkout@v4

      - name: Configurar GraalVM (Comunidad)
        uses: graalvm/setup-graalvm@v1
        with:
          java-version: '17'
          distribution: 'graalvm-community'
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install Android SDK
        uses: android-actions/setup-android@v3

      - name: Build con Maven
        run: |
          # Aumentamos la RAM para que GraalVM no sufra
          export MAVEN_OPTS="-Xmx6g"
          # Ejecutamos el build
          mvn clean gluonfx:build gluonfx:package -Pandroid -e

      - name: Guardar APK
        uses: actions/upload-artifact@v4
        with:
          name: KardexMobil-APK
          # Ajustamos la ruta para que coincida con donde Gluon deja el archivo
          path: target/gluonfx/aarch64-android/gvm/*.apk